services:
  laty_gui_runpod:
    build: .
    image: laty_gui_runpod:latest
    container_name: laty_gui_runpod_container
    ports:
      - "7866:7866"
      - "8888:8888"
    volumes:
      - .:/workspace/laty_gui:rw
      - ~/.cache/huggingface:/root/.cache/huggingface
    working_dir: /workspace/laty_gui
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]